apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: external-scaler-scaledobject
  namespace: default
  labels:
    deploymentName: external-scaler
spec:
  scaleTargetRef:
    deploymentName: external-scaler
  triggers:
  - type: external
    metadata:
      # Required
      serviceURI: external-scaler-redis
      # Optional
      address: REDIS_HOST
      password: REDIS_PASSWORD
      listName: mylist
      listLength: "5"