apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-redis-external-scaler
  namespace: keda
spec:
  selector:
    matchLabels:
      service: keda-redis-external-scaler
  replicas: 1
  template:
    metadata:
      labels:
        service: keda-redis-external-scaler
    spec:
      containers:
      - image: patnaikshekhar/redisexternalscaler:1.2
        name: scaler
        env:
        - name: CERT_PATH
          value: /certs
        volumeMounts:
        - name: certs
          mountPath: /certs
      volumes:
      - name: certs
        secret:
          secretName: keda-redis-external-scaler