apiVersion: v1
kind: Service
metadata:
  name: redis-external-scaler-service
  namespace: keda
spec:
  selector:
    service: keda-redis-external-scaler
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080